name: rani-ukamble-group/multi_yml
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
    - run: echo "Building the application..."
  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
    - run: echo "Running tests..."
